name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v4
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: Create output
        run: sh ./build.sh
      - name: Inspect output
        run: ls -la output
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN_KEY }}
        with:
          source-directory: 'output'
          destination-github-username: sinryuji
          destination-repository-name: clean-coast-frontend
          user-name: github-actions[bot]
          user-email: ${{ secrets.ACCOUNT_EMAIL }}
          commit-message: ${{ github.event.head_commit.message || 'Update from main branch' }}
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
